apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation
  labels:
    app: installation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: installation
  template:
    metadata:
      labels:
        app: installation
    spec:
      containers:
        - name: installation
          image: 740569282574.dkr.ecr.ap-southeast-2.amazonaws.com/puri-installation:v3
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5