server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** /orderStatuses/**
        - id: Assignment
          uri: http://localhost:8082
          predicates:
            - Path=/assignments/** 
        - id: Installation
          uri: http://localhost:8083
          predicates:
            - Path=/installations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/** /orderStatuses/**
        - id: Assignment
          uri: http://assignment:8080
          predicates:
            - Path=/assignments/** 
        - id: Installation
          uri: http://installation:8080
          predicates:
            - Path=/installations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080